on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge main into vercel-prod
      run: |
          git fetch --unshallow
          git checkout vercel-prod
          git pull
          git merge --no-ff origin/main -m "Auto-merge main into vercel-prod"
          git push